export const config = {
  connection: {
    port: 5432,
    host: 'localhost',
    database: 'nick',
    user: 'nick',
    password: 'nick',
  },
  blobsDir: `${__dirname}/blobs`,
  port: 8000,
  secret: 'secret',
  systemUsers: ['admin', 'anonymous'],
  systemGroups: ['Owner'],
  supportedLanguages: ['en', 'nl'],
  defaultLanguage: 'en',
  clientMaxSize: '64mb',
  imageScales: {
    large: [768, 768],
    preview: [400, 400],
    mini: [200, 200],
    thumb: [128, 128],
    tile: [64, 64],
    icon: [32, 32],
    listing: [16, 16],
  },
  cors: {
    allowOrigin: '*',
    allowMethods: '*',
    allowHeaders: '*',
    allowCredentials: true,
    exposeHeaders: '*',
    maxAge: 3660,
  },
  mailServer: {
    host: 'localhost',
    port: 587,
    secure: false,
    auth: {
      user: 'someuser',
      pass: 'somepadd',
    },
  },
  mailDebug: true,
};
