source "https://rubygems.org"
gem "jekyll", "~> 3.9.0"
gem "webrick", "~> 1.7"
gem "jekyll-rtd-theme", "~> 2.0.10"
gem "github-pages", group: :jekyll_plugins

group :jekyll_plugins do
  gem "jekyll-default-layout"
  gem "jekyll-readme-index"
  gem "jekyll-github-metadata"
  gem "jekyll-titles-from-headings"
  gem "jemoji"
  gem "jekyll-avatar"
  gem "jekyll-mentions"
end
