name: Changelog
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - main
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check for changelog entry
        uses: dangoslen/changelog-enforcer@v2
        with:
          changeLogPath: 'CHANGELOG.md'
          skipLabels: 'Skip-Changelog'
