name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: nick
          POSTGRES_PASSWORD: nick
          POSTGRES_DB: nick
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4

      # Node setup
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Bootstrap application
      - name: Bootstrap application
        run: yarn bootstrap

      # Run tests
      - name: Run tests
        run: yarn test
